const itemList = [
  {
    item: "Empire State Building",
    itemID: 1,
    price: 129.99,
    qunatity: 1,
    manufacturer: "Lego",
    category: "Architecture",
    openingStock: 100,
    reorderPoint: 10,
    pic: "images/empire-state-building.jpeg",
  },

  {
    item: "Statue of Liberty",
    itemID: 2,
    price: 119.99,
    qunatity: 1,
    manufacturer: "Lego",
    category: "Architecture",
    openingStock: 100,
    reorderPoint: 10,
    pic: "images/statue-of-liberty.jpeg",
  },

  {
    item: "Shanghai",
    itemID: 3,
    price: 59.99,
    qunatity: 1,
    manufacturer: "Lego",
    category: "Architecture",
    openingStock: 100,
    reorderPoint: 10,
    pic: "images/shanghai.jpeg",
  },

  {
    item: "Tokyo",
    itemID: 4,
    price: 59.99,
    qunatity: 1,
    manufacturer: "Lego",
    category: "Architecture",
    openingStock: 100,
    reorderPoint: 10,
    pic: "images/tokyo.jpeg",
  },

  {
    item: "Paris",
    itemID: 5,
    price: 49.99,
    qunatity: 1,
    manufacturer: "Lego",
    category: "Architecture",
    openingStock: 100,
    reorderPoint: 10,
    pic: "images/paris.jpeg",
  },

  {
    item: "The White House",
    itemID: 6,
    price: 99.99,
    qunatity: 1,
    manufacturer: "Lego",
    category: "Architecture",
    openingStock: 100,
    reorderPoint: 10,
    pic: "images/the-white-house.jpeg",
  },

  {
    item: "Trafalgar Square",
    itemID: 7,
    price: 79.99,
    qunatity: 1,
    manufacturer: "Lego",
    category: "Architecture",
    openingStock: 100,
    reorderPoint: 10,
    pic: "images/trafalger-square.jpeg",
  },

  {
    item: "Dubai",
    itemID: 8,
    price: 59.99,
    qunatity: 1,
    manufacturer: "Lego",
    category: "Architecture",
    openingStock: 100,
    reorderPoint: 10,
    pic: "images/dubai.jpeg",
  },

  {
    item: "New York",
    itemID: 9,
    price: 59.99,
    qunatity: 1,
    manufacturer: "Lego",
    category: "Architecture",
    openingStock: 100,
    reorderPoint: 10,
    pic: "images/new-york-city.jpeg",
  },

  {
    item: "San Francisco",
    itemID: 10,
    price: 49.99,
    qunatity: 1,
    manufacturer: "Lego",
    category: "Architecture",
    openingStock: 100,
    reorderPoint: 10,
    pic: "images/san-francisco.jpeg",
  },

  {
    item: "Las Vegas",
    itemID: 11,
    price: 39.99,
    qunatity: 1,
    manufacturer: "Lego",
    category: "Architecture",
    openingStock: 100,
    reorderPoint: 10,
    pic: "images/las-vegas.jpeg",
  },

  {
    item: "London",
    itemID: 12,
    price: 39.99,
    qunatity: 1,
    manufacturer: "Lego",
    category: "Architecture",
    openingStock: 100,
    reorderPoint: 10,
    pic: "images/london.jpeg",
  },
];

export default itemList;
